version: "3.9"

services:
  vllm-qwen8b:
    image: vllm/vllm-openai:latest
    container_name: vllm-qwen-8b
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LC_ALL=C.UTF-8
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    shm_size: '8gb' # Tăng bộ nhớ chia sẻ cho model lớn hơn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model Qwen/Qwen2.5-7B-Instruct-AWQ
      --trust-remote-code
      --dtype auto
      --gpu-memory-utilization 0.9
      --max-model-len 16384
      --enable-auto-tool-choice
      --tool-call-parser hermes
      --quantization awq
    restart: unless-stopped